### ISSUE TITLE
pretrained model is not available for downloading

### ISSUE THREAD

**Issue by jasonfjptchh0821** [HongwenZhang/PyMAF#111]

**Comment by ZhenyanSun** [comment]
> _No description provided._

Have you found the pretrained model？I met the same error

**Comment by HongwenZhang** [comment]
Hi, the pretrained model is still available at [colab](https://colab.research.google.com/drive/11RXLsH9BdoSCwY6G-IX7KgqDxVoImu6K?usp=sharing#scrollTo=Plo2YZZmaDtY)

`wget --no-check-certificate "https://onedrive.live.com/download?cid=DF2414B28D1B6A99&resid=DF2414B28D1B6A99%21862&authkey=AJqiZVYmJa6jgoU" -O pymaf_data_for_demo.zip`

**Comment by ZhenyanSun** [comment]
> https://onedrive.live.com/download?cid=DF2414B28D1B6A99&resid=DF2414B28D1B6A99%21862&authkey=AJqiZVYmJa6jgoU

Thx very much.

**Comment by MaiPhuong21** [comment]
@HongwenZhang Hi, Link you provide above not exist. Where can I get pretrained model?

**Comment by HongwenZhang** [comment]
The pretrained model remains available for downloading, see:
https://github.com/HongwenZhang/PyMAF?tab=readme-ov-file#necessary-files
https://drive.google.com/drive/folders/1zeJ_Z5GS6d7EEKXuZTRFCyF2xFOo7V5w
