### ISSUE TITLE
[Question] n_iter in Regressor.forward

### ISSUE THREAD

**Issue by tdelort** [HongwenZhang/PyMAF#12]
Hi !

I have a question about the `n_iter` parameter of the `Regressor` class. Did you try to bump up that number higher than `1` and what was the effect on the results ?

**Comment by HongwenZhang** [comment]
Hi, thanks for your question. We did not try higher values but such a setting should bring some gains.

**Comment by tdelort** [comment]
Ok ! Thank you for your quick answer !
