### ISSUE TITLE
Mesh-aligned Features

### ISSUE THREAD

**Issue by zhihaolee** [HongwenZhang/PyMAF#13]
Hi, 

You use the projected points to extract mesh-aligned feature, have you tried to just concat the projected image and the feature maps? Would it be better because it retains all the features and let the network learn how to combine them?

Thanks!

**Comment by HongwenZhang** [comment]
Hi, thanks for your proposal! We did not try such a strategy. Concatenating the projected image with feature maps may be feasible but also need additional convolutions to process and combine them.

**Comment by zhihaolee** [comment]
Thanks for your reply, maybe it worths a try
