### ISSUE TITLE
question about per channel pixel-noise augmentation strategy

### ISSUE THREAD

**Issue by leon532** [HongwenZhang/PyMAF#14]
请教一下，per channel pixel-noise这个augmentation主要是针对什么问题呢？我理解是可以提升网络输出旋转角的稳定性？这个augmentation策略对于结果是否有明显的收益呢？ 是否可以分享一下，感谢

**Comment by HongwenZhang** [comment]
你好，这个主要是对输入图像的颜色做的augmentation，这种augmentation在图像处理相关任务中是比较常用的做法，一般2D/3D姿态估计网络的训练中都有这个augmentation操作
