### ISSUE TITLE
how  to  download  J_regressor_extra.npy

### ISSUE THREAD

**Issue by APeiZou** [HongwenZhang/PyMAF#16]
![image](https://user-images.githubusercontent.com/49524647/130223048-4ee47848-ad7c-418b-b56e-86141b677062.png)
how  to  download  J_regressor_extra.npy?

**Comment by HongwenZhang** [comment]
Hi, the necessary files should be ready by following the instruction at https://github.com/HongwenZhang/PyMAF#necessary-files.
It seems that the preprocessed data from SPIN was missing in your case.
