### ISSUE TITLE
Single image and demo?

### ISSUE THREAD

**Issue by YangJae96** [HongwenZhang/PyMAF#17]
Hello. Thank you for sharing your great work.
I have ran your demo code, but it looks like it only supports video?

I just want to render a single person 3D mesh reconstruction with different viewpoints. For more detail, I want it like below example images.
![0002_c1s1_000451_03](https://user-images.githubusercontent.com/57695621/130270472-dc66d211-5d86-40c9-b473-9a06a3f1e89c.jpg)
![0002_c1s1_000451_03](https://user-images.githubusercontent.com/57695621/130270414-0ad1319f-6038-4bec-90ad-d2027e669665.jpg)

How can I do this?? Could you give me some advice.

Thanks in advance!.

**Comment by HongwenZhang** [comment]
Hi, the demo code now supports a single image input. Please refer to the README for the example usage.

**Comment by YangJae96** [comment]
Thank you so much!!
