### ISSUE TITLE
import neural_renderer

### ISSUE THREAD

**Issue by ketsu-shan** [HongwenZhang/PyMAF#19]
ImportError: /root/anaconda3/envs/pymaf/lib/python3.6/site-packages/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
cuda 9.0 torch 1.1.0 why this package not compatible with this version when run the demo which input photo?

**Comment by HongwenZhang** [comment]
Hi, the neural_renderer is not needed for the demo. You can disable related import when running the demo.
