### ISSUE TITLE
Are you planning to make a google colab version?

### ISSUE THREAD

**Issue by cedro3** [HongwenZhang/PyMAF#2]
Are you planning to make a google colab version?

**Comment by Tina-Husky** [comment]
Thank you for your suggestion! We started getting down to deploy PyMAF on the colab. Now it's available, so check it out :)
https://colab.research.google.com/drive/11RXLsH9BdoSCwY6G-IX7KgqDxVoImu6K?usp=sharing#scrollTo=Plo2YZZmaDtY

**Comment by cedro3** [comment]
It's so cool! With this, many people can try it. Thank you so much.
This issue has been resolved.
