### ISSUE TITLE
how to get finnal_fits/xxx.npz

### ISSUE THREAD

**Issue by nanfengguli** [HongwenZhang/PyMAF#24]
Hello, I would like to know how did you get the file finnal_fits/xxx.npz required during the training?
I want to train the model in my own dataset.
thanks

**Comment by a139122679** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data/final_fits/lsp-orig.npz'                                                                                               Is lsp-orig.npz or lspet.npz in the spin_fits.tar.gz package that I downloaded?

**Comment by HongwenZhang** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'data/final_fits/lsp-orig.npz' Is lsp-orig.npz or lspet.npz in the spin_fits.tar.gz package that I downloaded?

Yes.

**Comment by a139122679** [comment]
ok，thank you very much.

**Comment by liangwx** [comment]
学长，lsp-orig.npz就是  lsp.npz吗？

**Comment by HongwenZhang** [comment]
> 

应该就是lsp-orig.npz

**Comment by h-s-dev** [comment]
@HongwenZhang 

I retrieved spin_fits.tar.gz from the SPIN web page, but it does not seem to contain lsp-orig.npz.
The following files are included when spin_fits.tar.gz is extracted.
coco.npz
lsp.npz
lspet.npz
mpii.npz
mpi_inf_3dhp.npz

Please share lsp-orig.npz to the following email.
w.blue.light.w@gmail.com

By the way, the URL of SPIN's final fits is as follows
https://github.com/nkolot/SPIN#final-fits

>Final fits
We also release the improved fits that our method produced at the end of SPIN training. You can download them from [here](http://visiondata.cis.upenn.edu/spin/spin_fits.tar.gz). Each .npz file contains the pose and shape parameters of the SMPL model for the training examples, following the order of the training .npz files. For each example, a flag is also included, indicating whether the quality of the fit is acceptable for training (following an automatic heuristic based on the joints reprojection error).

spin_fits.tar.gz was obtained from here quoted above
http://visiondata.cis.upenn.edu/spin/spin_fits.tar.gz

**Comment by Italy2006** [comment]
> @HongwenZhang
> 
> I retrieved spin_fits.tar.gz from the SPIN web page, but it does not seem to contain lsp-orig.npz. The following files are included when spin_fits.tar.gz is extracted. coco.npz lsp.npz lspet.npz mpii.npz mpi_inf_3dhp.npz
> 
> Please share lsp-orig.npz to the following email. [w.blue.light.w@gmail.com](mailto:w.blue.light.w@gmail.com)
> 
> By the way, the URL of SPIN's final fits is as follows https://github.com/nkolot/SPIN#final-fits
> 
> > Final fits
> > We also release the improved fits that our method produced at the end of SPIN training. You can download them from [here](http://visiondata.cis.upenn.edu/spin/spin_fits.tar.gz). Each .npz file contains the pose and shape parameters of the SMPL model for the training examples, following the order of the training .npz files. For each example, a flag is also included, indicating whether the quality of the fit is acceptable for training (following an automatic heuristic based on the joints reprojection error).
> 
> spin_fits.tar.gz was obtained from here quoted above http://visiondata.cis.upenn.edu/spin/spin_fits.tar.gz

请问你弄到了嘛？如果有的话方便发一份嘛？另外我还有疑问就是有没有其他数据集的资源啊

**Comment by HongwenZhang** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: 'data/final_fits/lsp-orig.npz' Is lsp-orig.npz or lspet.npz in the spin_fits.tar.gz package that I downloaded?
> 
> Yes.

 lsp.npz and lsp-orig.npz are the same one

**Comment by Italy2006** [comment]
> > > FileNotFoundError: [Errno 2] No such file or directory: 'data/final_fits/lsp-orig.npz' Is lsp-orig.npz or lspet.npz in the spin_fits.tar.gz package that I downloaded?
> > 
> > 
> > Yes.
> 
> lspet.npz and lsp-orig.npz are the same one

 Didn't you say that lsp-orig.npz and lsp.npz are  the same?

**Comment by HongwenZhang** [comment]
> > > > FileNotFoundError: [Errno 2] No such file or directory: 'data/final_fits/lsp-orig.npz' Is lsp-orig.npz or lspet.npz in the spin_fits.tar.gz package that I downloaded?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > lspet.npz and lsp-orig.npz are the same one
> 
> Didn't you say that lsp-orig.npz and lsp.npz are the same?

Sorry for my misspelling.

Clarification:
lsp-orig.npz is the lsp.npz in spin_fits.tar.gz.
spin_fits.tar.gz can be download from https://github.com/nkolot/SPIN#final-fits .
