### ISSUE TITLE
In basedataset.py

### ISSUE THREAD

**Issue by ketsu-shan** [HongwenZhang/PyMAF#26]
Why we need to self.keypoints = np.concatenate([keypoints_openpose, keypoints_gt], axis=1), concat the two list.What is the rule for openpose data?
thanks

**Comment by HongwenZhang** [comment]
Hi, the keypoint adopts the definition listed in [here](https://github.com/HongwenZhang/PyMAF/blob/master/core/constants.py#L15), which is followed [SPIN](https://github.com/nkolot/SPIN/blob/master/constants.py#L14).
