### ISSUE TITLE
About generate static_fits

### ISSUE THREAD

**Issue by ketsu-shan** [HongwenZhang/PyMAF#28]
Hi，I want to train with my own dataset but I didn't have the 3D groundtruth or corresponding smpl initial parameters. So how can I generate the static_fits and final_fits? What about these .npy file using for?
Thanks ;)

**Comment by HongwenZhang** [comment]
Hi, these .npy files are pseudo labels for training. The static_fits and final_fits are the SMPL parameters fitted by SMPLify and SPIN, respectively. These files are generated in [SPIN](https://github.com/nkolot/SPIN).
