### ISSUE TITLE
Confirmation about necessary files

### ISSUE THREAD

**Issue by cedro3** [HongwenZhang/PyMAF#3]
'Collect SMPL model files from https://smpl.is.tue.mpg.de and UP. Rename model files' means below ?

download `SMPL_Python_v1.1.0.zip`
    basicmodel_f_lbs_10_207_0_v1.1.0.pkl > SMPL_FEMALE.pkl
    basicmodel_m_lbs_10_207_0_v1.1.0.pkl > SMPL_MALE.pkl
 
download `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` > SMPL_NEUTRAL.pkl

**Comment by HongwenZhang** [comment]
Yes, that's right. Besides, the `SMPL_FEMALE.pkl` and `SMPL_MALE.pkl` are only used for the evaluation on 3DPW. The `SMPL_NEUTRAL.pkl` is sufficient for training, demo, and evaluation on other datasets.

**Comment by cedro3** [comment]
Thank you immediately answer! This issue has been resolved.

**Comment by unw9527** [comment]
Hi, thanks for your interesting work. I also want to confirm that whether "Fetch preprocessed data from SPIN" means running "fetch_data.sh" from SPIN's repository in ./data.

**Comment by HongwenZhang** [comment]
> Hi, thanks for your interesting work. I also want to confirm that whether "Fetch preprocessed data from SPIN" means running "fetch_data.sh" from SPIN's repository in ./data.

Hi, it means running the `fetch_data.sh` of SPIN under the PyMAF project directory `./`.
