### ISSUE TITLE
About MPJPE

### ISSUE THREAD

**Issue by ketsu-shan** [HongwenZhang/PyMAF#30]
Hi, I want to know the MPJPE is compyted on which space? Pixel space or real space? 
Why multiply 1000 in the code  like spin? What are their units and in your paper the number is after multiply 1000?
thank u ;)

**Comment by HongwenZhang** [comment]
Hi, the unit of MPJPE is millimeter (mm) in the real world. By multiplying 1000, the unit is converted from the meter (m) to millimeter (mm).

**Comment by ketsu-shan** [comment]
OK!
Another question if i use my dataset which gt like lsp datasets. which part need I modification like the joints map or some constant para? I  am train on my dataset then test it find all the mesh is slightly higer position and I used perspective_projection to  get my 2d coordinates a lot of negative values.
I uesd 18 keypoints openpose detected and my gt has 14 keypoints. Following is one of my output coordinates:


![捕获](https://user-images.githubusercontent.com/68980706/145166267-f35716da-6aed-41f7-b24a-bda9dc0a4882.PNG)

**Comment by ketsu-shan** [comment]
@HongwenZhang

**Comment by HongwenZhang** [comment]
Code for processing the SPIN-compatible data: https://github.com/nkolot/SPIN/tree/master/datasets/preprocess
