### ISSUE TITLE
checkpoint error

### ISSUE THREAD

**Issue by littlejiumi** [HongwenZhang/PyMAF#31]
Traceback (most recent call last):
  File "/root/Downloads/PyMAF/demo.py", line 569, in <module>
    run_image_demo(args)
  File "/root/Downloads/PyMAF/demo.py", line 85, in run_image_demo
    model.load_state_dict(checkpoint['model'], strict=False)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PyMAF:
	size mismatch for regressor.0.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).
	size mismatch for regressor.1.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).
	size mismatch for regressor.2.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).

**Comment by HongwenZhang** [comment]
Hi, This error is raised by the mismatched version of SMPL. PyMAF used the SMPL model with 10 shape PCs. Please refer to [#4 ](https://github.com/HongwenZhang/PyMAF/issues/4#issuecomment-824709755).
