### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/final_fits/h36m.npy'

### ISSUE THREAD

**Issue by SaterZhan** [HongwenZhang/PyMAF#35]
Hello, there is a problem that 'FileNotFoundError: [Errno 2] No such file or directory: 'data/final_fits/h36m.npy' when i start training the model, and there is not such file in final-fits in SPIN, where can i get this file ?  And if u have this ，please send me at saterzhan@163.com，3Q so much

**Comment by HongwenZhang** [comment]
Hi, the message has been sent.
