### ISSUE TITLE
does it need detection on image of every human first?

### ISSUE THREAD

**Issue by jinfagang** [HongwenZhang/PyMAF#36]
does it need detection on image of every human first?

**Comment by HongwenZhang** [comment]
Yes, the demo code includes the person detection on the given input image.

**Comment by jinfagang** [comment]
@HongwenZhang thanks. Does it need 2d keypoints?

**Comment by HongwenZhang** [comment]
No, keypoint detection is not needed.

**Comment by jinfagang** [comment]
@HongwenZhang thanks. How's the e2e speed compare with TCMR and HyperIK?

**Comment by jinfagang** [comment]
@HongwenZhang How's the final visual effect compare with TCMR and PyMAF?

**Comment by HongwenZhang** [comment]
I vote for PyMAF.

**Comment by jinfagang** [comment]
@HongwenZhang thanks. PyMAF seems incrediable stable in terms of temporal smooth. TCMR can not achieves this effect even it using a GRU temporal model style. What do you think plays most important role in this strong result?

And, do u think it is needed for keypoint2d input for event better result? Did u tried it?

**Comment by HongwenZhang** [comment]
@jinfagang Thanks for your interest. PyMAF leverages the spatial information better via the mesh-aligned features, which helps better mesh-image alignment even it does not use temporal information. I have not tried using 2D key points in our method but I think it is worth a try.

**Comment by hust-kevin** [comment]
@HongwenZhang, infer spedd really slow, run a 200-frame(single-person) need 2-min

**Comment by HongwenZhang** [comment]
@hust-kevin This is because the visualization (rendering) of SMPL is slow.

**Comment by hust-kevin** [comment]
@HongwenZhang yes, visualization is slow, what' more, the result in whole-body is good, but the upper body result is bad, any suggestion to improve upper body result?

**Comment by HongwenZhang** [comment]
@hust-kevin For partial body recovery, our previous work [DaNet](https://github.com/HongwenZhang/DaNet-3DHumanReconstruction) may be a better solution.
