### ISSUE TITLE
Unsuitable checkpoints

### ISSUE THREAD

**Issue by tsoydari** [HongwenZhang/PyMAF#4]
When I run demo.py I get an error:

Traceback (most recent call last):
  File "demo.py", line 460, in <module>
    main(args)
  File "demo.py", line 143, in main
    model.load_state_dict(checkpoint['model'], strict=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PyMAF:
	size mismatch for regressor.0.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).
	size mismatch for regressor.1.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).
	size mismatch for regressor.2.smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).

Can you give correct checkpoints?

**Comment by HongwenZhang** [comment]
Hi, the demo code and checkpoints work well on our machine and Colab (https://colab.research.google.com/drive/11RXLsH9BdoSCwY6G-IX7KgqDxVoImu6K?usp=sharing). 
The screenshot on Colab can be seen as follows.
It's recommended to have a try on the Colab first.
It's also suggested to have a check on the versions of pytorch and smplx, i.e., pytorch==1.1.0 and smplx==0.1.13.

![image](https://user-images.githubusercontent.com/12066626/114028123-b4327500-98aa-11eb-9627-9f0310b73694.png)

**Comment by HongwenZhang** [comment]
This error is raised by the mismatched version of `SMPL_NEUTRAL.pkl`. PyMAF used the SMPL model with 10 shape PCs, which can be downloaded from the official website or using the following script. 
`wget https://github.com/classner/up/raw/master/models/3D/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl data/smpl/SMPL_NEUTRAL.pkl`
