### ISSUE TITLE
Except downsizing the number of num_workers，what else can I do to control my use of memory

### ISSUE THREAD

**Issue by ShamLich** [HongwenZhang/PyMAF#40]
When I train that my process is always killed by the system, because of been out of memory during eval。

**Comment by HongwenZhang** [comment]
The evaluation code computes performances for each iteration. All intermediate results all stored during the evaluation which may lead to memory issues. Modifying the code to evaluate the final mesh only should use less memory.

**Comment by Fouksi** [comment]
Hi,

Can you please elaborate which part of the code  you are referring to?

**Comment by Janeweet** [comment]
Hi, thanks for the work. I met the same issue, the logger said my bin size was too small and recommended I increase max_face_per bin/max_points_per_bin or set the bin_size to 0 which is defined in pytorch3d. Is this suggestion the same as evaluating the final mesh? I monitored the 2080Ti single GPU and it was no more than 80% utilization while training but the CPU exploded to 1200% and more. Please give me some suggestions. Many thanks.

**Comment by Janeweet** [comment]
Hi, @HongwenZhang.Thanks for the work. I ran the trainer codes but memory overflowed.
<img width="736" alt="image" src="https://github.com/HongwenZhang/PyMAF/assets/131422180/59564d1f-9952-42fd-86a9-188958778bde">
I modified the code of fit method:
<img width="560" alt="image" src="https://github.com/HongwenZhang/PyMAF/assets/131422180/582f9d12-2669-4c11-8263-03c777c81426">
But I got the same overflow. Did I modify the right place to evaluate the final mesh?
Thanks for answering.

**Comment by Janeweet** [comment]
> When I train that my process is always killed by the system, because of been out of memory during eval。

Hi, have you solved this problem?

**Comment by ShamLich** [comment]
> > When I train that my process is always killed by the system, because of been out of memory during eval。
> 
> Hi, have you solved this problem?

yeah，I calculate the eval stage in multiple steps and then consolidate the results.
