### ISSUE TITLE
how to get 2d keypoints in image?

### ISSUE THREAD

**Issue by abcliguanxi** [HongwenZhang/PyMAF#42]
Firstly,Thks for your great work. I have three question.
1. you use weak perspective projection or perspective projection?
2. how to get 2d keypoints in image?
Looking forward to your reply！

**Comment by HongwenZhang** [comment]
1. We use weak perspective projection.
2. Keypoints can be obtained by the following code: https://github.com/HongwenZhang/PyMAF/blob/master/eval_coco.py#L134-L140

**Comment by abcliguanxi** [comment]
thks, i will closed this issus.
