### ISSUE TITLE
About focal_length=5000

### ISSUE THREAD

**Issue by CHENYUHANG-smp** [HongwenZhang/PyMAF#46]
Thanks for your brilliant work!
I notice that you estimate the camera parameters by using a function called "estimate_translation_np" (borrowed from SPIN). I feel puzzled that why you could set the same focal length (5000) for different datasets and different images. 
Thanks again and hope for your reply.

**Comment by HongwenZhang** [comment]
Hi, The focal length of 5000 is indeed not accurate. There are papers trying to tackle this problem:

Beyond Weak Perspective for Monocular 3D Human Pose Estimation, ECCV 2020
SPEC: Seeing People in the Wild with an Estimated Camera, ICCV 2021
