### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'image'

### ISSUE THREAD

**Issue by ywx-stack** [HongwenZhang/PyMAF#47]
Thanks for your brilliant work!
But when I train the first stage,I meet one error:
`Traceback (most recent call last):`
  `File "/media/data1/mypath/PyMAF/train.py", line 69, in <module>`
    `main(None, ngpus_per_node, options)`
  `File "/media/data1/mypath/PyMAF/train.py", line 38, in main`
  `  trainer.fit()`
  `File "/media/data1/mypath/PyMAF/core/trainer.py", line 502, in fit`
   ` self.train(epoch)`
  `File "/media/data1/mypath/PyMAF/core/trainer.py", line 294, in train`
    `self.visualize(self.step_count, batch, 'train', **out)`
  `File "/media/data1/mypath/anaconda3/envs/pymaf/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context`
    `return func(*args, **kwargs)`
  `File "/media/data1/mypath/PyMAF/core/trainer.py", line 681, in visualize`
    `addlight=True `
`TypeError: __call__() got an unexpected keyword argument 'image'`
`pymaf_res50_as_lp3_mlp256-128-64-5_May06-19-26-01-asJ Epoch 0:   0%| | 10/4877 [`

orginal `cfg.TRAIN_VIS_ITER_FERQ =1000`, when I set `cfg.TRAIN_VIS_ITER_FERQ =10`, got the same error.
Maybe there is no graphical interface on the remote server?
And my env:
Ubuntu20 
python 3.6.10
torch 1.8.0+cu11.1

**Comment by HongwenZhang** [comment]
Hi, there is a bug when calling the [renderer](https://github.com/HongwenZhang/PyMAF/blob/master/utils/renderer.py#L191). How about trying to modify `image=` to `img=` at [L679](https://github.com/HongwenZhang/PyMAF/blob/master/core/trainer.py#L679)?

**Comment by swerizwan** [comment]
render_imgs.append(self.renderer(
                smpl_verts,
                self.smpl.faces,
                img=img_vis,
                cam=cam_t,
                addlight=True
            ))

I modified the image to img, Now I am getting an error  
  File "/home/abbas/PYMAF/PyMAF-smpl/core/trainer.py", line 706, in visualize
    render_imgs.append(self.renderer(
TypeError: __call__() got an unexpected keyword argument 'addlight'
What do you suggest to do in order to fix that error?

**Comment by HongwenZhang** [comment]
@swerizwan Hi, it was a bug when updating the renderer. Simply removing the `addlight=True` should fix this error. Please see the commit https://github.com/HongwenZhang/PyMAF/commit/1b14b2da6a831fe903bc0658ec8fa65fd92b6047.
