### ISSUE TITLE
Question about training PyMAF

### ISSUE THREAD

**Issue by MooreManor** [HongwenZhang/PyMAF#48]
Hi, Hongwen! Thanks for your great job!

I have two questions about training PyMAF. 
1. 
> PyMAF is trained on Human3.6M at the first stage and then trained on the mixture of both 2D and 3D datasets at the second stage.

Why PyMAF needs to train on H36m first? And will PyMAF get comparable performance to the two-stage training method if PyMAF is trained only on mixed datasets?
2. 
In PyMAF, `num_epochs` is set to 200. Compared with other methods in HPS, the training procedure is too long. Is it possible to reduce the num of epochs to reduce the training time while keeping the performance?

**Comment by Italy2006** [comment]
> Hi, Hongwen! Thanks for your great job!
> 
> I have two questions about training PyMAF. 1.
> 
> > PyMAF is trained on Human3.6M at the first stage and then trained on the mixture of both 2D and 3D datasets at the second stage.
> 
> Why PyMAF needs to train on H36m first? And will PyMAF get comparable performance to the two-stage training method if PyMAF is trained only on mixed datasets? 2. In PyMAF, `num_epochs` is set to 200. Compared with other methods in HPS, the training procedure is too long. Is it possible to reduce the num of epochs to reduce the training time while keeping the performance?

Holy crap, Bin!!!!!!

**Comment by HongwenZhang** [comment]
> Hi, Hongwen! Thanks for your great job!
> 
> I have two questions about training PyMAF. 1.
> 
> > PyMAF is trained on Human3.6M at the first stage and then trained on the mixture of both 2D and 3D datasets at the second stage.
> 
> Why PyMAF needs to train on H36m first? And will PyMAF get comparable performance to the two-stage training method if PyMAF is trained only on mixed datasets? 2. In PyMAF, `num_epochs` is set to 200. Compared with other methods in HPS, the training procedure is too long. Is it possible to reduce the num of epochs to reduce the training time while keeping the performance?

Hi, we follow the training setting of SPIN. The num_epochs is just a maximum number, not the actual training setting.

**Comment by Italy2006** [comment]
> > Hi, Hongwen! Thanks for your great job!
> > I have two questions about training PyMAF. 1.
> > > PyMAF is trained on Human3.6M at the first stage and then trained on the mixture of both 2D and 3D datasets at the second stage.
> > 
> > 
> > Why PyMAF needs to train on H36m first? And will PyMAF get comparable performance to the two-stage training method if PyMAF is trained only on mixed datasets? 2. In PyMAF, `num_epochs` is set to 200. Compared with other methods in HPS, the training procedure is too long. Is it possible to reduce the num of epochs to reduce the training time while keeping the performance?
> 
> Hi, we follow the training setting of SPIN. The num_epochs is just a maximum number, not the actual training setting.

I have another question, I looked at the code, the network does not need to detect the position of the portrait first, but sends the whole image directly. In this situation, only one result will be output in the case of multiple people. How to supervise?

**Comment by tinatiansjz** [comment]
Hi, @Italy2006 
Actually, no matter at what phase, the whole image is first cropped based on the bounding box parameters and then fed to the network. The difference is that we use ground-truth bboxes in training, while during inference a detector is employed to detect them.

[https://github.com/HongwenZhang/PyMAF/blob/smpl/datasets/base_dataset.py#L164](https://github.com/HongwenZhang/PyMAF/blob/smpl/datasets/base_dataset.py#L164)
