### ISSUE TITLE
demo pose and shape bug

### ISSUE THREAD

**Issue by Xbbei** [HongwenZhang/PyMAF#5]
Hi, 
    Thank you share the great work about human pose and shape estimation. I run the project in my datasets, and use the output "pose" and "shape" parameters, I found it will create the weird 3d mesh. And I found the bug in the demo.py:
     Should change the 229 -> 230
                    pred_pose.append(output['theta'][:, 3:75].reshape(batch_size * seqlen, -1))
                    pred_betas.append(output['theta'][:, 75:].reshape(batch_size * seqlen, -1))
    to:
                    pred_pose.append(output['theta'][:, 13:85].reshape(batch_size * seqlen, -1))
                    pred_betas.append(output['theta'][:, 3:13].reshape(batch_size * seqlen, -1))

Thanks

**Comment by HongwenZhang** [comment]
Many thanks for your pointing this out! The `demo.py` has been updated now.
