### ISSUE TITLE
final_fits/h36m.npy and static_fits/h36m.npy

### ISSUE THREAD

**Issue by lai-pf** [HongwenZhang/PyMAF#51]
I can't get these two files, can someone send me a copy? It really helps me a lot. 
This is my email dr.henrylai@gmail.com  .  Thanks again.

**Comment by HongwenZhang** [comment]
Messages have been sent.

**Comment by h-s-dev** [comment]
@HongwenZhang 
Thank you for your recent response regarding the "h36m_mosh_train.npz".
Could you also send me the files "final_fits/h36m.npy" and "static_fits/h36m.npy" to the following e-mail address?
w.blue.light.w@gmail.com
Thanks again.

**Comment by yangyang32111** [comment]
@HongwenZhang 
Thanks for your excellent work,and Could you also send me the files "final_fits/h36m.npy" and "static_fits/h36m.npy" to the following e-mail ? Thankk again!
geyy@emails.bjut.edu.cn

**Comment by fmx789** [comment]
@HongwenZhang
Thanks for your excellent work,and Could you also send me the files "final_fits/h36m.npy" to the following e-mail ? Thanks again!
<fmx456@outlook.com>

**Comment by StancyMiller** [comment]
@HongwenZhang
Thanks for your excellent work,and Could you also send me the files "final_fits/h36m.npy" and "static_fits/h36m.npy"  to the following e-mail ? Thanks again!
2365366022@qq.com

**Comment by Britton-Li** [comment]
@HongwenZhang
Thanks for your excellent work,and Could you also send me the files "final_fits/h36m.npy" and "static_fits/h36m.npy" to the following e-mail ? libao2023@gmail.com
 Thanks again!
