### ISSUE TITLE
Release PyMAF-X

### ISSUE THREAD

**Issue by quqixun** [HongwenZhang/PyMAF#52]
When will you release the amazing PyMAF-X ?

**Comment by HongwenZhang** [comment]
Hi, thanks for your interest in our work. We do have a plan to release the code of PyMAF-X, but the exact time is to be determined. Maybe in a few weeks or months but not later than the time when the paper is accepted.

**Comment by HongwenZhang** [comment]
Hi, demo code for PyMAF-X is now released, please check out the [smplx branch](https://github.com/HongwenZhang/PyMAF/tree/smplx) or `git checkout smplx`.
