### ISSUE TITLE
.npy files

### ISSUE THREAD

**Issue by lalala68** [HongwenZhang/PyMAF#53]
Where should I get "J_regressor_extra.npy" ,"J_regressor_h36m.npy" and  "static_fits/ .npy" files？
Could you send me the files to the following e-mail address?
hiznzzn2@gmail.com
Thank you!

**Comment by HongwenZhang** [comment]
Hi, as described in README, some necessary files need to be accessed from SPIN.
https://github.com/HongwenZhang/PyMAF#necessary-files
https://github.com/nkolot/SPIN#fetch-data

The static_fits is not used in our code. We use the final_fits of SPIN, which can be downloaded from:
https://github.com/nkolot/SPIN#final-fits

**Comment by lalala68** [comment]
> Hi, as described in README, some necessary files need to be accessed from SPIN. https://github.com/HongwenZhang/PyMAF#necessary-files https://github.com/nkolot/SPIN#fetch-data
> 
> The static_fits is not used in our code. We use the final_fits of SPIN, which can be downloaded from: https://github.com/nkolot/SPIN#final-fits

Thank you！！！❤
