### ISSUE TITLE
Deploy on windows and Train

### ISSUE THREAD

**Issue by Zinia17** [HongwenZhang/PyMAF#54]
Hi, great work indeed. I am novice but have high interest to run this project. So I have the following questions.
1. Can I deploy this project by cloning in a windows machine?
2. Do you have any demo vedio for deploying in any machine?   
3. Can I train it for 3dPW dataset? 
4. How can I get the result that you showed in the table?
Hoping for your guidance.

**Comment by HongwenZhang** [comment]
Hi, thanks for your interest.
1. I have not tried to deploy it on Windows.
2. Unfortunately, we do not have such a video.
3. The training data of 3DPW need to be prepared in the same way as SPIN.
4. Both training and evaluation code are provided in this repository. You can follow the instruction in README to get the evaluation results.

**Comment by Zinia17** [comment]
Thanks a lot for the clarifications.
