### ISSUE TITLE
What is the inference time for a single frame of the Pymaf-x model?

### ISSUE THREAD

**Issue by JACKYLUO1991** [HongwenZhang/PyMAF#55]
What is the inference time for a single frame of the Pymaf-x model?

**Comment by JACKYLUO1991** [comment]
Sorry, I just saw that the paper was given.

**Comment by JACKYLUO1991** [comment]
ValueError: Invalid device ID (0) in pyrender?

**Comment by mch0dmin** [comment]
> ValueError: Invalid device ID (0) in pyrender?

hi @JACKYLUO1991 , how did you solve this problem? thanks!
