### ISSUE TITLE
How can I get trans from output.pkl?

### ISSUE THREAD

**Issue by surheaven** [HongwenZhang/PyMAF#59]
What I ended up with was a video and a .pkl file. I found that the output.pkl has beta and pose without trans. So I want to ask how to get the trans of smpl?

**Comment by HongwenZhang** [comment]
Hi, the translation can be obtained from [here](https://github.com/HongwenZhang/PyMAF/blob/smplx/utils/renderer.py#L169).

**Comment by surheaven** [comment]
Thanks！
