### ISSUE TITLE
About training on Human3.6M：How to get 'data/final_fits/h36m.npy'?

### ISSUE THREAD

**Issue by sillyboyKK** [HongwenZhang/PyMAF#60]
Thank you very much for your amazing work! When I train pymaf on single dataset(Human3.6M), I don‘t know how to get 'data/final_fits/h36m.npy'

> 

       # Load dictionary 
        for ds_name, ds in train_dataset.dataset_dict.items():
            if ds_name in ['h36m']:
                dict_file = os.path.join(path_config.FINAL_FITS_DIR, ds_name + '.npy')
                self.fits_dict[ds_name] = torch.from_numpy(np.load(dict_file))
                self.valid_fit_state[ds_name] = torch.ones(len(self.fits_dict[ds_name]), dtype=torch.uint8)

**Comment by HongwenZhang** [comment]
Please refer to [#27](https://github.com/HongwenZhang/PyMAF/issues/27#issuecomment-974158282).
