### ISSUE TITLE
How to get h36m_mosh_train.npz

### ISSUE THREAD

**Issue by xljh0520** [HongwenZhang/PyMAF#62]
Hi, thanks for sharing your code. I'm trying to reproduce your work. I tried to train it on Human3.6M dataset. However, I could not find the h36m_mosh_train.npz. Could your tell me how to get it?

**Comment by HongwenZhang** [comment]
Hi, please refer to [#27](https://github.com/HongwenZhang/PyMAF/issues/27#issuecomment-974158282).
