### ISSUE TITLE
install openpifpaf error

### ISSUE THREAD

**Issue by Guanyuansheng** [HongwenZhang/PyMAF#63]
Hi! I'm having trouble when installing the 'openpifpaf==0.13.1' in requirements.txt, and there are many errors occurred when I run the command 'pip3 install openpifpaf==0.13.1':
ERROR: Failed building wheel for openpifpaf  
Failed to build openpifpaf  
ERROR: Could not build wheels for openpifpaf, which is required to install pyproject.toml-based projects

Can you explain how to solve this problem? thank you very much!

**Comment by HongwenZhang** [comment]
Hi, you may need to check the version of PyTorch or install openpifpaf from the source files.

**Comment by Celulean** [comment]
Hi, it works when you update your python to 3.8.10

**Comment by Guanyuansheng** [comment]
ok!&nbsp;Thanks a lot for your answer!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HongwenZhang/PyMAF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HongwenZhang/PyMAF] install openpifpaf error (Issue #63)





 
Hi, it works when you update your python to 3.8.10
