### ISSUE TITLE
How to align openpifpaf keypoints and  SMPLX joints?

### ISSUE THREAD

**Issue by yijicheng** [HongwenZhang/PyMAF#64]
Thans for your excellent work!

How to align openpifpaf keypoints(127) and  SMPLX joints(127/144)?

**Comment by HongwenZhang** [comment]
Hi, the keypoint definitions of openpifpaf and SMPL-X can be found at:
https://github.com/jin-s13/COCO-WholeBody
https://github.com/openpifpaf/openpifpaf/blob/main/src/openpifpaf/plugins/wholebody/constants.py#L71
https://github.com/HongwenZhang/PyMAF/blob/smplx/core/constants.py#L192
