### ISSUE TITLE
Question about regressor's output in each iteration

### ISSUE THREAD

**Issue by fmx789** [HongwenZhang/PyMAF#66]
Hi, once more thanks for your fantastic work!
I noticed that your method have different regressors for each iteration, and the output from the previous iteration serves as the input to the following regressor. How do you prevent the output of the regressor from diverging (i.e., moving further away from GT)?
According to what I understand, you saved the output of each iteration and then calculating the loss and back propagating in each batch. I wondered whether this would address the above issue.
Thanks again!

**Comment by HongwenZhang** [comment]
Hi, as shown in previous work like HMR and SDM, such an iterative update strategy typically converges after training.

**Comment by fmx789** [comment]
Thanks for your reply, I got it!

**Comment by fmx789** [comment]
Thanks for your reply, I got it!
