### ISSUE TITLE
About pretrained model on coco

### ISSUE THREAD

**Issue by yangyang32111** [HongwenZhang/PyMAF#68]
Hi,sorry to bother you,can you  please share the pretrained model which named  'data/pretrained_model/pose_resnet_50_256x192.pth.tar' ? thank you very much!

**Comment by HongwenZhang** [comment]
Hi, the coco pre-trained model can be downloaded from https://github.com/Microsoft/human-pose-estimation.pytorch. 
Please also refer to Issue #58.

**Comment by yangyang32111** [comment]
Thanks for your quick reply ! 
:)

**Comment by yangyang32111** [comment]
Sorry to bother you again, I have a question that when using new training strategy (coco-eft) the smpl model is the same as before in pymaf(using human first) ?  Because I found that PARE's SMPL model seems a bit different.

**Comment by HongwenZhang** [comment]
Hi, the SMPL model should be the same, but I am not so sure about that.
