### ISSUE TITLE
Is it able to achieve real-time speed?

### ISSUE THREAD

**Issue by sylyt62** [HongwenZhang/PyMAF#74]
Is seems like this architecture is designed more based on images, but just wondering, if it is possible to do inference in real time? How about get rid of visualization?

**Comment by HongwenZhang** [comment]
Hi, PyMAF can run in real time when using tools like TensorRT. Moreover, the mesh-aligned features require only a downsampled mesh of the SMPL. Using a sparse SMPL and precomputing the initialization of the mean-pose SMPL could also speed up the inference, see: https://github.com/HongwenZhang/PyMAF/blob/smpl/models/pymaf_net.py#L276

**Comment by sylyt62** [comment]
Thanks, I will give it a try~
