### ISSUE TITLE
Some question about the initial pose of body and hand

### ISSUE THREAD

**Issue by henrycjh** [HongwenZhang/PyMAF#76]
Thanks for your great work! 
I have learned that the SMPL-X use the pose parameters to get the final pose from the initial pose (T-Pose), and the pose parameters for each joints is the axis-angle format rotation relative to its parent's rotation. However, I have no detail information about the actual initial coordinate of each joints, including body and hands (especially for the hands). I have tried to search in the original paper, but still got nothing. 
Here is an example that I would like to know about the initial coordinates.
![joint-coordinates](https://user-images.githubusercontent.com/73419275/208062772-1d0baef0-f387-41e6-8878-26c2148f818a.png)
Is there any documentation about it? 
Thanks for your attention!

**Comment by HongwenZhang** [comment]
Hi, do you mean the joint coordinates in T-pose?

**Comment by henrycjh** [comment]
Yes, do you have any idea?
