### ISSUE TITLE
Update object tracking/detection model

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [HongwenZhang/PyMAF#78]
I used to update the detection/tracking algorithm to use recently released yolo v8. It detects the human with a way better accuracy. Indeed the accuracy jump is obvious. I'm wondering if a pr regarding detector/tracker will be appreciated? Cleaning and refactoring the codes takes some times and I don't want to confront with a rejected pr. If there are some restrictive code of conduct or some inhibitive rules like that please let me know.

Regards

**Comment by HongwenZhang** [comment]
Hi @hajix, a pr regarding a better detector/tracker is very appreciated. Please make it an option to use the original detector. Thanks!

**Comment by mohamad-hasan-sohan-ajini** [comment]
I'll take it into account.
