### ISSUE TITLE
ValueError: Invalid device ID (0)

### ISSUE THREAD

**Issue by lllllialois** [HongwenZhang/PyMAF#79]
```
Traceback (most recent call last):
  File "/home/dande/projects/PyMAF/demo.py", line 573, in <module>
    run_image_demo(args)
  File "/home/dande/projects/PyMAF/demo.py", line 98, in run_image_demo
    renderer = PyRenderer(resolution=(constants.IMG_RES, constants.IMG_RES))
  File "/home/dande/projects/PyMAF/utils/renderer.py", line 83, in __init__
    self.renderer = pyrender.OffscreenRenderer(
  File "/home/dande/anaconda3/envs/pymafx/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/dande/anaconda3/envs/pymafx/lib/python3.8/site-packages/pyrender/offscreen.py", line 137, in _create
    egl_device = egl.get_device_by_index(device_id)
  File "/home/dande/anaconda3/envs/pymafx/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
    raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)
```
Does anybody miss this bug? I only have one GPU whose number is 0, I don't know why it will tell me an Invalid device ID. 
My environment is:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
chumpy                    0.70                     pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cudatoolkit               11.1.1              ha002fc5_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.33                  pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filterpy                  1.4.5                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
freetype-py               2.3.0                    pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
imageio                   2.25.0                   pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
intel-openmp              2022.1.0          h9e868ea_3769    defaults
iopath                    0.1.10                   pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2    defaults
json-tricks               3.16.1                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100             h7f98852_1001    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libiconv                  1.17                 h166bdaf_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtiff                   4.1.0                h2733197_1    defaults
libuv                     1.43.0               h7f98852_0    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib                3.6.3                    pypi_0    pypi
mkl                       2022.1.0           hc2b9512_224    defaults
multi-person-tracker      0.1                      pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  3.0                      pypi_0    pypi
ninja                     1.11.0               h924138e_0    conda-forge
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.7.0.68                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1s               h7f8727e_0    defaults
packaging                 23.0                     pypi_0    pypi
pillow                    7.1.2            py38hb39fc2d_0    defaults
pip                       22.3.1           py38h06a4308_0    defaults
portalocker               2.7.0                    pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
pycocotools               2.0                      pypi_0    pypi
pyglet                    2.0.4                    pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrender                  0.1.45                   pypi_0    pypi
python                    3.8.16               h7a1cb2a_2    defaults
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
pytorch3d                 0.7.2                    pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.10.0                   pypi_0    pypi
setuptools                65.6.3           py38h06a4308_0    defaults
six                       1.16.0                   pypi_0    pypi
smplx                     0.1.28                   pypi_0    pypi
sqlite                    3.40.1               h5082296_0    defaults
tabulate                  0.9.0                    pypi_0    pypi
tensorboardx              2.5.1                    pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
tifffile                  2023.2.3                 pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
torchgeometry             0.1.2                    pypi_0    pypi
torchvision               0.10.0               py38_cu111    pytorch
tqdm                      4.64.1                   pypi_0    pypi
trimesh                   3.18.3                   pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.10               h5eee18b_1    defaults
yacs                      0.1.8                    pypi_0    pypi
yolov3                    0.1                      pypi_0    pypi
zipp                      3.12.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults
zstd                      1.4.9                ha95c52a_0    conda-forge

```

**Comment by lllllialois** [comment]
ok， It seems that there has some elusive bug with the egl. According to [the docs](https://pyrender.readthedocs.io/en/latest/examples/offscreen.html) of pyrender, we can use osmesa instead of egl.
![image](https://user-images.githubusercontent.com/105269874/217167831-f3a4b5f6-1acf-4b39-872f-85c7cd7e2839.png)
change
`os.environ['PYOPENGL_PLATFORM'] = 'egl'`
into
`os.environ['PYOPENGL_PLATFORM'] = 'osmesa'`
to use osmesa.
see the [docs](https://pyrender.readthedocs.io/en/latest/install/index.html#installmesa) to learn how to install osmesa.

```
sudo apt update
sudo apt-get install llvm-6.0 freeglut3 freeglut3-dev
sudo wget https://github.com/mmatl/travis_debs/raw/master/xenial/mesa_18.3.3-0.deb
sudo dpkg -i ./mesa_18.3.3-0.deb || true
sudo apt install -f
```
or
`sudo wget --no-check-certificate https://github.com/mmatl/travis_debs/raw/master/xenial/mesa_18.3.3-0.deb`

then
```
git clone https://github.com/mmatl/pyopengl.git
pip install ./pyopengl
```
if meet
`ValueError: operands could not be broadcast together with shapes (224,224,2)  (224,224,3)`
change `output_img = rgb[:, :, :-1] * valid_mask * self.vis_ratio + (1 - valid_mask * self.vis_ratio) * item` into
`output_img = rgb[:, :, :] * valid_mask * self.vis_ratio + (1 - valid_mask * self.vis_ratio) * item`

**Comment by unbravely** [comment]
now i have new bug `ImportError: ('Unable to load OpenGL library', '/usr/lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0', 'libOSMesa.so.8', 'libOSMesa.so.8')`

**Comment by forrest-lam** [comment]
> ok， It seems that there has some elusive bug with the egl. According to [the docs](https://pyrender.readthedocs.io/en/latest/examples/offscreen.html) of pyrender, we can use osmesa instead of egl. ![image](https://user-images.githubusercontent.com/105269874/217167831-f3a4b5f6-1acf-4b39-872f-85c7cd7e2839.png) change `os.environ['PYOPENGL_PLATFORM'] = 'egl'` into `os.environ['PYOPENGL_PLATFORM'] = 'osmesa'` to use osmesa. see the [docs](https://pyrender.readthedocs.io/en/latest/install/index.html#installmesa) to learn how to install osmesa.
> 
> ```
> sudo apt update
> sudo apt-get install llvm-6.0 freeglut3 freeglut3-dev
> sudo wget https://github.com/mmatl/travis_debs/raw/master/xenial/mesa_18.3.3-0.deb
> sudo dpkg -i ./mesa_18.3.3-0.deb || true
> sudo apt install -f
> ```
> 
> or `sudo wget --no-check-certificate https://github.com/mmatl/travis_debs/raw/master/xenial/mesa_18.3.3-0.deb`
> 
> then
> 
> ```
> git clone https://github.com/mmatl/pyopengl.git
> pip install ./pyopengl
> ```
> 
> if meet `ValueError: operands could not be broadcast together with shapes (224,224,2) (224,224,3)` change `output_img = rgb[:, :, :-1] * valid_mask * self.vis_ratio + (1 - valid_mask * self.vis_ratio) * item` into `output_img = rgb[:, :, :] * valid_mask * self.vis_ratio + (1 - valid_mask * self.vis_ratio) * item`

how centos install osmesa? Where is the osmesa rpm package? I have some trouble on building from source.

**Comment by Kelu007** [comment]
> > ok， It seems that there has some elusive bug with the egl. According to [the docs](https://pyrender.readthedocs.io/en/latest/examples/offscreen.html) of pyrender, we can use osmesa instead of egl. ![image](https://user-images.githubusercontent.com/105269874/217167831-f3a4b5f6-1acf-4b39-872f-85c7cd7e2839.png) change `os.environ['PYOPENGL_PLATFORM'] = 'egl'` into `os.environ['PYOPENGL_PLATFORM'] = 'osmesa'` to use osmesa. see the [docs](https://pyrender.readthedocs.io/en/latest/install/index.html#installmesa) to learn how to install osmesa.
> > ```
> > sudo apt update
> > sudo apt-get install llvm-6.0 freeglut3 freeglut3-dev
> > sudo wget https://github.com/mmatl/travis_debs/raw/master/xenial/mesa_18.3.3-0.deb
> > sudo dpkg -i ./mesa_18.3.3-0.deb || true
> > sudo apt install -f
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or `sudo wget --no-check-certificate https://github.com/mmatl/travis_debs/raw/master/xenial/mesa_18.3.3-0.deb`
> > then
> > ```
> > git clone https://github.com/mmatl/pyopengl.git
> > pip install ./pyopengl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if meet `ValueError: operands could not be broadcast together with shapes (224,224,2) (224,224,3)` change `output_img = rgb[:, :, :-1] * valid_mask * self.vis_ratio + (1 - valid_mask * self.vis_ratio) * item` into `output_img = rgb[:, :, :] * valid_mask * self.vis_ratio + (1 - valid_mask * self.vis_ratio) * item`
> 
> how centos install osmesa? Where is the osmesa rpm package? I have some trouble on building from source.

Did you solve this? I also tried to install osmesa on centos but failed.
