### ISSUE TITLE
ImportError: cannot import name 'download_youtube_clip' from 'utils.demo_utils'

### ISSUE THREAD

**Issue by tdelort** [HongwenZhang/PyMAF#8]
I think that during one of the past 2 commits, the `demo.py` file was not changed according to the `utils/demo_utils.py` API.

"download_youtube_clip" has been renamed to "download_url" but the name hasn't been changed in the import statement on `demo.py`.

**Comment by Tina-Husky** [comment]
Sorry for the error I failed to notice. It's kind of you to correct it directly. I really appreciate it. 😊
(But, maybe some typos still exist... Feel free to ask for questions and give advice.)
