### ISSUE TITLE
OpenDRenderer 

### ISSUE THREAD

**Issue by wangxihao** [HongwenZhang/PyMAF#80]
Hi，when I run eval.py and eval_coco.py ,    an error happened that is  ''ImportError: cannot import name 'OpenDRenderer' from 'utils.renderer' '',  and I found that OpenDRenderer is not defined in renderer.py , so what should I do , thank you !

**Comment by zxk19981227** [comment]
Same Problem, waiting for a solution

**Comment by HongwenZhang** [comment]
`OpenDRenderer` can be found at `utils/renderer.py` of the historical version:
https://github.com/HongwenZhang/PyMAF/blob/19ad21c0006fb92004b7d4d553ec9687044efd03/utils/renderer.py#L165

OpenDRenderer is only needed for the visualization or the evaluation of segmentation. Related imports can be removed in common cases.

In the updated version, `IUV_Renderer` can play a similar role to render segmentation/IUV maps:
https://github.com/HongwenZhang/PyMAF/blob/smpl/utils/renderer.py#L432
