### ISSUE TITLE
在coco数据上训练需要计算smpl模型损失吗？

### ISSUE THREAD

**Issue by APeiZou** [HongwenZhang/PyMAF#81]
@HongwenZhang 您好，很棒的工作，请教一下在coco数据上训练需要计算smpl模型损失吗？

**Comment by HongwenZhang** [comment]
您好，在coco数据上需要使用伪SMPL标签数据计算smpl模型的损失

**Comment by APeiZou** [comment]
@HongwenZhang coco上的伪标签有提供吗？代码里面具体怎么生成啊
