### ISSUE TITLE
about datasets preprocessing

### ISSUE THREAD

**Issue by PGogo** [HongwenZhang/PyMAF#83]
Hi, thank you for your great work and sharing.
I wonder how do you preprocess the datasets that not mentioned in SPIN such as agora and 3doh50k.
It would be great if you could share the code in case of missing detail by myself.

**Comment by HongwenZhang** [comment]
Hi, thanks for your interest in our work. SPIN has provided example codes to preprocess several datasets. The preprocess of other datasets is quite similar.

**Comment by PGogo** [comment]
Thanks for the prompt reply!
