### ISSUE TITLE
Error happens when training on single dataset  'LSP'

### ISSUE THREAD

**Issue by wangxihao** [HongwenZhang/PyMAF#86]
Hi,  sorry to trouble you again. When I trains on single dataset  'LSP' whose label file  is lsp_dataset_original_train.npz , 
an error occurs:`ValueError: could not broadcast input array from shape (0,0,3) into shape (251,321,3)`. 
Further locate the problem， it locates on ` new_img[new_y[0]:new_y[1], new_x[0]:new_x[1]] = img[old_y[0]:old_y[1], old_x[0]:old_x[1]] `  .Though printing the vars,  when  old_y[0] is bigger than old_y[1] and old_x[0] is bigger than old_x[1], the error happens.   And when I run other datasets , it works well. It's so cunfusing , I'm wondering if I've set it up wrong，thank you !

**Comment by Britton-Li** [comment]
@wangxihao I meet the same error, maybe related to 'LSP' dataset. I think you have some empty image in it. Can you show me you dataset source?

**Comment by HongwenZhang** [comment]
Hi, I have uploaded the LSP dataset used in my code at:
[https://cloud.tsinghua.edu.cn/f/727fd2ca30244166a70d](https://cloud.tsinghua.edu.cn/f/727fd2ca30244166a70d)

**Comment by wangxihao** [comment]
> @wangxihao I meet the same error, maybe related to 'LSP' dataset. I think you have some empty image in it. Can you show me you dataset source?
The dataset I used was inherited, sorry I don't know the source either.

**Comment by wangxihao** [comment]
> @wangxihao I meet the same error, maybe related to 'LSP' dataset. I think you have some empty image in it. Can you show me you dataset source?

The dataset I used was inherited, sorry I don't know the source either.

**Comment by wangxihao** [comment]
> Hi, I have uploaded the LSP dataset used in my code at: https://cloud.tsinghua.edu.cn/f/727fd2ca30244166a70d

Thank you and I will have a try.
