### ISSUE TITLE
Definition: related to SMPL-X 

### ISSUE THREAD

**Issue by Britton-Li** [HongwenZhang/PyMAF#88]
Hello! I am trying to train **pymafx** with a smplx annotation, but there is a difference between the **smplx parameter** in base_dataset.py and the official definition. Such as pose:[N,72] in your definition and root_pose[N，3],body_pose[N, 63] in official definition. Can you show me the difference and how to transfer?

**Comment by HongwenZhang** [comment]
Hi, pose:[N,72] means the poses of 24 joints, including the `L_Hand` and `R_Hand`. For PyMAF-X, only 21 body joints are considered in body_pose[N, 63] (excluding the `L_Hand` and `R_Hand`). The poses of `L_Hand` and `R_Hand` will be considered in the hand-only prediction.
