### ISSUE TITLE
demo.py   need resnet50-19c8e357.pth 

### ISSUE THREAD

**Issue by Timkeeper2018** [HongwenZhang/PyMAF#89]
when I try to using this code " python3 demo.py --checkpoint=data/pretrained_model/PyMAF_model_checkpoint.pt --img_file examples/COCO_val2014_000000019667.jpg "
it said  " ValueError: data/pretrained_model/resnet50-19c8e357.pth is not exist!   "

**Comment by HongwenZhang** [comment]
Hi, the pre-trained ResNet model can be downloaded at:
`https://download.pytorch.org/models/resnet50-19c8e357.pth`
