### ISSUE TITLE
Evaluation results and protocol of 3DPW

### ISSUE THREAD

**Issue by HospitableHost** [HongwenZhang/PyMAF#90]
Hello, thank you so much for open sourcing such a nice work (PyMAF, ICCV 2021).
I use your pretrained model to evaluate on the dataset 3DPW(test split), but obtain a different result from the paper.
![image](https://user-images.githubusercontent.com/44576391/224992313-cb80829a-6354-4504-bd78-67a0c2f7c502.png)
![image](https://user-images.githubusercontent.com/44576391/224992423-4c40bd38-4120-44ae-b137-ea8b65fa0915.png)
So do you know where i am wrong?

**Comment by HospitableHost** [comment]
In addition, I used VIBE's framework for evaluation.

**Comment by HongwenZhang** [comment]
Hi, is the gender models used in the evaluation? Besides, is the root position subtracted for the PVE evaluation?

**Comment by HospitableHost** [comment]
> Hi, is the gender models used in the evaluation? Besides, is the root position subtracted for the PVE evaluation?

Hey, in order to avoid mistakes, I specially used all npz files in your project to replace the vibe ones. So the gender model is the same.
PVE evaluation I used is VIBE code. And expect for PVE, MPJPE PA-MPJPE are both bad.
I just use PyMAF model to replace VIBE class, and make sure that the interface is consistent.

**Comment by HongwenZhang** [comment]
Hi, have you used the PyMAF code to perform the evaluation? It may help to find out the reason causing the difference.

**Comment by HospitableHost** [comment]
> Hi, have you used the PyMAF code to perform the evaluation? It may help to find out the reason causing the difference.

Yes, I used the PyMAF code to perform the evaluation, and I find that the data you use is not exactly the same as that of VIBE, although they are all from the test set.

**Comment by HongwenZhang** [comment]
We follow the data and code of SPIN to conduct the evaluation of PyMAF. I have not tested it on the VIBE data and code.

**Comment by HongwenZhang** [comment]
It seems that this issue is related to more than one repository such as VIBE and SPIN. I temporally close this issue. Please feel free to reopen it if anyone has more related information.
