### ISSUE TITLE
NameError: name 'IUV_Renderer' is not defined

### ISSUE THREAD

**Issue by github1838** [HongwenZhang/PyMAF#91]
when i run th train code with this command :CUDA_VISIBLE_DEVICES=0 python3 train.py --regressor pymaf_net --single_dataset --misc TRAIN.BATCH_SIZE 64
error like this:

INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Failed to import *opendr*.
fail to import Renderer.
INFO:utils.train_utils:log name: logs/pymaf_res50/pymaf_res50_as_lp3_mlp256-128-64-5_Mar20-22-54-34-uOS
INFO:models.pose_resnet:=> loading pretrained model data/pretrained_model/pose_resnet_50_256x192.pth.tar
INFO:models.pose_resnet:loaded ResNet coco pretrained model
INFO:datasets.base_dataset:len of coco-full: 74834
INFO:datasets.base_dataset:len of 3dpw: 35515
/home/wz/anaconda3/envs/pymaf/lib/python3.8/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 12, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
No renderer for visualization.
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    main(None, ngpus_per_node, options)
  File "train.py", line 37, in main
    trainer = Trainer(options)
  File "/home/wz/PyMAF/core/base_trainer.py", line 28, in __init__
    self.init_fn()
  File "/home/wz/PyMAF/core/trainer.py", line 151, in init_fn
    self.iuv_maker = IUV_Renderer(output_size=cfg.MODEL.PyMAF.DP_HEATMAP_SIZE)
NameError: name 'IUV_Renderer' is not defined

**Comment by github1838** [comment]
I worked it after install opendr

**Comment by Veni-VidiVici-xiaoxu** [comment]
which version of opendr do you used,I tried but in vain
