### ISSUE TITLE
how can smoothing be achieved from frame to frame

### ISSUE THREAD

**Issue by balabalaboy** [HongwenZhang/PyMAF#92]
Thank you for your outstanding contribution, but I would like to ask a question. For video input, how can smoothing be achieved from frame to frame?

**Comment by HongwenZhang** [comment]
Hi, PyMAF runs frame-by-frame and does not use any post-processing operation to smooth the results.

**Comment by KevinGoodman** [comment]
maybe this would help, you can do the postprocess on predicted result like this
```python
 if args.smooth_type != 'None':
     from mmhuman3d.utils.demo_utils import smooth_process
     smooth_cfg_dir = 'xxx'
     pred_pose = smooth_process(pred_pose.cpu().numpy().reshape(-1, 24, 3), args.smooth_type, smooth_cfg_dir).reshape(-1, 72)
```

**Comment by balabalaboy** [comment]
> Hi, PyMAF runs frame-by-frame and does not use any post-processing operation to smooth the results.

I know your video is reconstructed frame by frame, but it seems that the mesh between the reconstructed frames is very natural and does not wobble too much when large deformation occurs or when it remains static. So I would like to ask if you did not apply any smoothing measures between frames to ensure the smoothness of the mesh display after frame reconstruction?

**Comment by HongwenZhang** [comment]
> maybe this would help, you can do the postprocess on predicted result like this
> 
> ```python
>  if args.smooth_type != 'None':
>      from mmhuman3d.utils.demo_utils import smooth_process
>      smooth_cfg_dir = 'xxx'
>      pred_pose = smooth_process(pred_pose.cpu().numpy().reshape(-1, 24, 3), args.smooth_type, smooth_cfg_dir).reshape(-1, 72)
> ```

Thank you.

**Comment by HongwenZhang** [comment]
> > Hi, PyMAF runs frame-by-frame and does not use any post-processing operation to smooth the results.
> 
> I know your video is reconstructed frame by frame, but it seems that the mesh between the reconstructed frames is very natural and does not wobble too much when large deformation occurs or when it remains static. So I would like to ask if you did not apply any smoothing measures between frames to ensure the smoothness of the mesh display after frame reconstruction?

We do not apply any smoothing term to improve the smoothness in our method or code. As the predicted meshes of our method are aligned with the images in most cases, PyMAF produces more visually plausible results than previous video-based methods.

**Comment by balabalaboy** [comment]
> We do not apply any smoothing term to improve the smoothness in our method or code. As the predicted meshes of our method are aligned with the images in most cases, PyMAF produces more visually plausible results than previous video-based methods.

Thank you very much！ Is it possible for pymaf to reconstruct in real time？It seems that single-frame reconstruction is speedy.

**Comment by HongwenZhang** [comment]
With acceleration tools such as TensorRT, PyMAF can run in real-time. Meanwhile, as the reprojection requires much fewer points than the original SMPL mesh, a sparse version of SMPL could also speed up the reconstruction.

**Comment by balabalaboy** [comment]
> With acceleration tools such as TensorRT, PyMAF can run in real-time. Meanwhile, as the reprojection requires much fewer points than the original SMPL mesh, a sparse version of SMPL could also speed up the reconstruction.

ok！
