### ISSUE TITLE
Failed to inference single image

### ISSUE THREAD

**Issue by CiaoHe** [HongwenZhang/PyMAF#93]
Hi, I'm new to this area but glad to see this wonderful project.

I'm trying to use `demo.py` to inference a single image, like below
![pose1_smpl](https://user-images.githubusercontent.com/39040787/227415756-4bfba000-6f64-496d-8c4e-8694c28e8e7f.png)

However, when I'm running the `demo.py` with command 
```bash
python3 demo.py --checkpoint=data/pretrained_model/PyMAF_model_checkpoint.pt --img_file examples/pose1.png
```
The result front view is original image and the side view result is purely nothing(black)

![pose1_smpl](https://user-images.githubusercontent.com/39040787/227415902-fa49041b-9438-4e41-96f4-2b0d401dec59.png)
![pose1_smpl_side](https://user-images.githubusercontent.com/39040787/227415914-eddd38a3-e9a4-4f61-a88c-163a8ed41777.png)

I've tried the demo video inference and everything's OK. I just wonder how to solve this problem.

Best,

**Comment by HongwenZhang** [comment]
Hi, have you tried other images such as those example images provided by the repository?

**Comment by CiaoHe** [comment]
I've just tried to inference `examples/COCO_val2014_000000019667.jpg`, but still failed like above:
![COCO_val2014_000000019667_smpl](https://user-images.githubusercontent.com/39040787/227770412-a0cfac8e-64cf-425a-8c78-5db580fd0350.png) front

![COCO_val2014_000000019667_smpl_side](https://user-images.githubusercontent.com/39040787/227770398-61fb83e0-22bf-4600-899e-21af9ed29709.png) side

With debugging, I found that `img_shape` from the render is same with `img_np`, which means rendering failed
https://github.com/HongwenZhang/PyMAF/blob/11fc5c1a4459ba2396433c9a8a902341cdcbb020/demo.py#L119-L125

I've tried the colab demo, everything's fine.
I'm trying to fix this problem. Thx for your reply!
