### ISSUE TITLE
About the results in Agora's Leaderboard

### ISSUE THREAD

**Issue by henrycjh** [HongwenZhang/PyMAF#99]
Hi, thanks for your great work. I used your demo code in smplx branch to test the test set of Agora, the results are much worse than your results in the Leaderboard. I am wondering if there is a gap between the model used in demo and the model used in paper, or the detection model.

**Comment by HongwenZhang** [comment]
Hi, thank you for your interest in our work. We finetuned our model on AGORA and evaluated the results on AGORA. Unfortunately, the finetuned model has not been made available. We hope this could clarify this issue.
